export enum ENV {
  EXPO_PUBLIC_API_URL = 'EXPO_PUBLIC_API_URL',
  EXPO_PUBLIC_KEY_PUSHER = 'EXPO_PUBLIC_KEY_PUSHER',
  EXPO_PUBLIC_CLUSTER_PUSHER = 'EXPO_PUBLIC_CLUSTER_PUSHER'
}

export enum SECURE_STORE_KEY {
  AUTH = 'AUTH'
}
